config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root 'static_page#index'

  get '/little-berlins', to: 'static_page#littleberlin'

  #get '/article', to: 'static_page#article'

resources :article  #, only: [:index, :show, :edit, :new]
resources :categorie #, only: [:show]

resources :comment
resources :like

resources :article do
    resources :avatars, only: [:create]
    resources :comment
    resources :like
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  belongs_to :categorie
  has_many :likes
  has_many :comments

  has_one_attached :avatar

end

app/models/categorie.rb
class Categorie < ApplicationRecord

  has_many :articles
  
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :article
  
end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :article
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/article_controller.rb
class ArticleController < ApplicationController

  # before_action :is_admin?, only: :new  


  def index

    #@article = Article.all.order('created_at DESC')


      @articles = Article.all.order('created_at DESC')

      @visages = Categorie.find(1).articles.all.limit(4).order('created_at DESC')

      @engages = Categorie.find(2).articles.all.limit(4).order('created_at DESC')

      @experts = Categorie.find(3).articles.all.limit(4).order('created_at DESC')


  end


  def new


  end


  def create

    @article = Article.new(title: params[:title], subject: params[:subject], content:params[:content], img_desc: params[:img_desc], categorie_id: 1)

          if @article.save
            redirect_to root_path
            flash[:success] = "La article a bien été ajoutée."
          else
            redirect_to new_article_path
            flash[:success] = "Une erreur est survenue, veuillez renseigner tous les champs obligatoires. Si la valeure est nule, indiquer '0'"
          end

  end



  def show


    @article = Article.find(params[:id])

    @comments = Article.find(params[:id]).comments.all

    @likes = Article.find(params[:id]).likes.all


    @visages = Categorie.find(1).articles.all.limit(4).order('created_at DESC')

    @engages = Categorie.find(2).articles.all.limit(4).order('created_at DESC')

    @experts = Categorie.find(3).articles.all.limit(4).order('created_at DESC')


  end




  def edit
  # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
  @articleup = Article.find(params[:id])


  end



  def update
  # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
  # pour info, le contenu de ce formulaire sera accessible dans le hash params
  # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)

  @articleup = Article.find(params[:id])



      if @articleup.update(title: params[:title], subject: params[:subject], content:params[:content], img_desc: params[:img_desc])
        redirect_to article_path
      else
        render :edit
      end

  end





  def destroy
    # Méthode qui récupère le potin concerné et le détruit en base
    # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
    @articledel = Article.find(params[:id])


      if @articledel.destroy
        redirect_to article_index_path
      else
        redirect_to article_path
      end


    end


    def is_admin?
      # check if user is a admin
      # if not admin then redirect to where ever you want
      redirect_to root_path unless current_user.is_admin == true
    end




end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController


  def create
    @article = Article.find(params[:article_id])
    @article.avatar.attach(params[:avatar])
    redirect_to(article_path(@article))
  end


end

app/controllers/categorie_controller.rb
class CategorieController < ApplicationController


  def show

    @articles = Categorie.find(params[:id]).articles.all
    
    @categorie = Categorie.find(params[:id])

    @visages = Categorie.find(1).articles.all.limit(4).order('created_at DESC')

    @engages = Categorie.find(2).articles.all.limit(4).order('created_at DESC')

    @experts = Categorie.find(3).articles.all.limit(4).order('created_at DESC')



  end





end

app/controllers/comment_controller.rb
class CommentController < ApplicationController


  def new


  end


  def create

    @article = Article.find(params[:article_id])
     @comment = @article.comments.new(pseudo:params[:pseudo],comment_content: params[:comment_content])

    if @comment.save
      redirect_to article_path(@article)
      flash[:success] = "La article a bien été ajoutée."
    else
      redirect_to article_index_path(params[:id])
      flash[:success] = "Une erreur est survenue, veuillez renseigner tous les champs obligatoires. Si la valeure est nule, indiquer '0'"
    end

  end


end

app/controllers/like_controller.rb
class LikeController < ApplicationController

  def new


  end


  def create

    @article = Article.find(params[:article_id])
     @like = @article.likes.new

    if @like.save
      redirect_to article_path(@article)
      flash[:success] = "La article a bien été ajoutée."
    else
      redirect_to article_index_path(params[:id])
      flash[:success] = "Une erreur est survenue, veuillez renseigner tous les champs obligatoires. Si la valeure est nule, indiquer '0'"
    end

  end

end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController

  def index

    @articles_last = Article.all.limit(4).order('created_at DESC')

  end

  def blog

  end


  def article

  end

  def littleberlin

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/categorie_helper.rb
module CategorieHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/views/article/edit.html.erb
<div class="col-xs-12 col-sm-12 col-md-10 col-lg-10 mx-auto" style="margin-top:8em;">

    <h2 class="col-12 text-left mb-4 title-ajouts">Modifier l'article :</h2>

    <%= form_tag url_for(action:'update'), method: "patch" do %>

    <div class="col-lg-12 ">
      <span>Titre de l'article</span>
      <div class="form-group contact-block1">
        <%= text_field_tag 'title', @articleup.title,  class:"form-control icon-file" %>
      </div>
    </div>


    <div class="col-lg-12 ">
      <span>Titre de l'article</span>
      <div class="form-group contact-block1">
        <%= text_area_tag 'subject', @articleup.subject,  class:"form-control icon-file" %>
      </div>
    </div>

    <div class="col-lg-12 ">
      <span>Titre de l'article</span>
      <div class="form-group contact-block1">
        <%= text_area_tag 'img_desc', @articleup.img_desc,  class:"form-control icon-file" %>
      </div>
    </div>


    <div class="col-lg-12 my-4">
      <div class="form-group">
        <span>Contenu</span>
        <%= text_area_tag 'content', @articleup.content,  class:"form-control icon-euro", id:"post_body_edit" %>
      </div>
      <trix-editor input="post_body_edit"></trix-editor>

    </div>



    <div class="col-6 mt-4 text-right">
      <%= submit_tag "Mettre à jour l'article", class:"btn btn-form", style:"border-radius:20px; margin:2em 0;"  %>

    <% end %>
    </div>



    </div>

app/views/article/new.html.erb
<div class="col-xs-12 col-sm-12 col-md-10 col-lg-10 mx-auto" style="margin-top:8em;">

    <h2 class="col-12 text-left mb-4 title-ajouts">Ajouter un nouvel article :</h2>


      <%= form_tag url_for(article_index_path), :article => @article, method: 'post',class:"register-form" do %>
        <div class="row">

          <div class="col-lg-12 my-4">
            <div class="form-group contact-block1">
              <%= text_field_tag 'title', nil, placeholder: 'titre', class:"form-control "%>
            </div>
          </div>


          <div class="col-lg-12 my-4">
            <div class="form-group contact-block1">
              <%= text_area_tag 'subject', nil, placeholder: 'Description courte', class:"form-control ", rows:"3"%>
            </div>
          </div>

          <div class="col-lg-12 my-4">
            <div class="form-group contact-block1">
              <%= text_area_tag 'img_desc', nil, placeholder: 'Description image mise en avant', class:"form-control ", rows:"3"%>
            </div>
          </div>

          <div class="col-lg-12">
            <div class="form-group">
              <%= text_area_tag 'content', nil , placeholder: 'Contenu',  class:"form-control " , id:'post_body', rows:"8" %>
            </div>
            <trix-editor input="post_body"></trix-editor>
          </div>



          <div class="col-lg-3 mt-2 text-right ">
            <%= submit_tag " Ajouter ", class: "btn-get-started scrollto", style:"border-radius:20px;" %>
            <%end%>
          </div>


          </div>

    </div>

app/views/article/show.html.erb
    <!--================Home Banner Area =================-->
    <section class="banner_area">
      <div class="banner_inner d-flex align-items-center">
        <div class="container">
          <div
            class="banner_content d-md-flex justify-content-between align-items-center"
          >
          <div class="page_link">
            <a href="<%=root_path%>">Accueil</a>
            <a href="<%=categorie_path(1)%>"><%=@article.categorie.categorie_name%></a>
          </div>
            <div class="mb-3 mb-md-0">
              <h2></h2>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!--================End Home Banner Area =================-->




<!--================Blog Area =================-->
<section class="blog_area single-post-area area-padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 posts-list">
                <div class="single-post">
                    <div class="feature-img">

                      <h2><%=@article.title%></h2>
                      <ul class="blog-info-link mt-3 mb-4">
                          <li><a href="<%=categorie_path(1)%>"> <%=@article.categorie.categorie_name%></a></li>
                          <li><a><i class="far fa-comments"></i> <%=@article.comments.count%> Commentaire(s)</a></li>
                      </ul>


                      <% if current_user.nil? %>

                      <%elsif current_user.is_admin == true%>

                        <div style="display:flex;">
                            <a class="mr-4" href="<%=edit_article_path(@article.id)%>">Editer l'article</a><br>
                            <a href="<%= article_path(@article)%>" class="btn-outline red" data-confirm="Êtes vous sûr de vouloir supprimer cet article ?" data-method="DELETE" >Supprimer l'article</a>
                        </div>

                    <%else%>

                    <%end%>


                      <p><%=@article.subject%></p>


                      <%if @article.avatar.attached?%>
                        <%= image_tag @article.avatar, alt: 'avatar', style:"height:35em;width:100%;object-fit:cover;" %>
                      <%else%>
                        <%=image_tag "home.jpg", style:"height:30em;width:100%;object-fit:cover;"%>
                      <%end%>

                      <p><%=@article.img_desc%></p>

                    </div>

                    <% if current_user.nil?%>

                    <%elsif current_user.is_admin == true %>
                      <h3>Changer d'avatar ?</h3>
                      <%= form_tag article_avatars_path(@article), multipart: true do %>
                        <%= file_field_tag :avatar %>
                        <%= submit_tag "mettre à jour" %>
                      <% end %>


                    <%else%>

                    <%end%>


                    <div class="blog_details">

                        <%= sanitize @article.content%>

                    </div>
                </div>
                <div class="navigation-top">
                    <div class="d-sm-flex justify-content-between text-center">
                        <p class="like-info"><span class="align-middle"><i class="far fa-heart"></i></span><%=@likes.count%> </p>
                        <div class="col-sm-4 text-center my-2 my-sm-0">
                            <p class="comment-count"><span class="align-middle"><i class="far fa-comment"></i></span> <%=@comments.count%> Commentaires</p>
                        </div>
                    </div>

                </div>


                <div class="comments-area">
                    <h4><%=@comments.count%> Commentaire(s)</h4>
                    <div class="comment-list">

                      <% @comments.each do |i|%>

                        <div class="single-comment justify-content-between d-flex">
                            <div class="user justify-content-between d-flex">

                                <div class="desc">
                                    <p class="comment">
                                        <%=i.comment_content%>
                                    </p>

                                    <div class="d-flex justify-content-between">
                                        <div class="d-flex align-items-center">
                                            <h5>
                                                <%=i.pseudo%>
                                            </h5>
                                            <p class="date">December 4, 2017 at 3:12 pm </p>
                                        </div>

                                    </div>

                                </div>
                            </div>
                        </div>
                        <%end%>

                    </div>
                </div>




                <div class="comment-form">
                    <h4>Laisser un commentaire</h4>

                    <%= form_tag url_for(article_comment_index_path(params[:id])), :comment => @comment, method: 'post',class:"register-form" do %>
                      <div class="row">

                        <div class="col-lg-12 my-4">
                          <div class="form-group contact-block1">
                            <%= text_field_tag 'pseudo', nil, placeholder: 'Pseudo', class:"form-control "%>
                          </div>
                        </div>


                        <div class="col-lg-12 ">
                          <div class="form-group contact-block1">
                            <%= text_area_tag 'comment_content', nil, placeholder: 'Votre commentaire', class:"form-control ", rows:"3"%>
                          </div>
                        </div>


                        <div class="ml-4 mt-2 text-right ">
                          <%= submit_tag " Ajouter ", class:"button button-contactForm", style:"border-radius:20px;" %>
                          <%end%>
                        </div>


                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="blog_right_sidebar">

                  <aside class="single_sidebar_widget popular_post_widget">
                      <h3 class="widget_title">Visages</h3>

                      <% @visages.each do |i|%>
                      <div class="media post_item">
                        <%if i.avatar.attached?%>
                          <%= image_tag i.avatar, alt: 'avatar', style:"width:7em;height:6em;object-fit:cover;" %>
                        <%else%>
                          <%=image_tag "home.jpg", style:"width:7em;height:6em;object-fit:cover;"%>
                        <%end%>
                          <div class="media-body">
                              <a href="<%=article_path(i)%>">
                                  <h3><%=i.title%></h3>
                              </a>
                              <p><%=i.created_at.strftime("Le %d/%m/%Y")%></p>
                          </div>
                      </div>
                      <%end%>

                  </aside>

                    <aside class="single_sidebar_widget popular_post_widget">
                        <h3 class="widget_title">Les Engagés</h3>

                        <% @engages.each do |i|%>
                        <div class="media post_item">
                          <%if i.avatar.attached?%>
                            <%= image_tag i.avatar, alt: 'avatar' , style:"width:7em;height:6em;object-fit:cover;"%>
                          <%else%>
                            <%=image_tag "home.jpg", style:"width:7em;height:6em;object-fit:cover;"%>
                          <%end%>
                            <div class="media-body">
                                <a href="<%=article_path(i)%>">
                                    <h3><%=i.title%></h3>
                                </a>
                                <p><%=i.created_at.strftime("Le %d/%m/%Y")%></p>
                            </div>
                        </div>
                        <%end%>

                    </aside>


                    <aside class="single_sidebar_widget popular_post_widget">
                        <h3 class="widget_title">Les Experts</h3>

                        <% @experts.each do |i|%>
                        <div class="media post_item">
                          <%if i.avatar.attached?%>
                            <%= image_tag i.avatar, alt: 'avatar', style:"width:7em;height:6em;object-fit:cover;" %>
                          <%else%>
                            <%=image_tag "home.jpg", style:"width:7em;height:6em;object-fit:cover;"%>
                          <%end%>
                            <div class="media-body">
                                <a href="<%=article_path(i)%>">
                                    <h3><%=i.title%></h3>
                                </a>
                                <p><%=i.created_at.strftime("Le %d/%m/%Y")%></p>
                            </div
                        </div>
                        <%end%>

                    </aside>


                    <aside class="single_sidebar_widget newsletter_widget">
                        <h4 class="widget_title">Vous avez aimé l'article ?</h4>
                        <div >
                          <%= form_tag url_for(article_like_index_path(params[:id])), :like => @like, method: 'post',class:"register-form" do %>
                            <div class="row">
                              <%= button_tag(type: 'submit', class: "button button-contactForm2") do %>
                              J'<i class="far fa-heart"></i>
                                <% end %>
                              <%end%>

                            </div>
                        </div>
                    </aside>

                </div>
            </div>
        </div>
    </div>
</section>
<!--================Blog Area end =================-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Le Mot de la Bombe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

        <script src="https://kit.fontawesome.com/2f609438b2.js" crossorigin="anonymous"></script>

        <meta name="viewport" content="width=device-width, initial-scale=1">



  </head>


  <!--================ Start header Top Area =================-->
  <section class="header-top">
  <div class="container">
      <div class="row align-items-center justify-content-between">
          <div class="col-6 col-lg-4">
              <div class="float-left">
                  <ul class="header_social">
                    <li><a href="https://www.linkedin.com/in/alice-gleizes-588642114/?originalSubdomain=fr"><i class="fab fa-linkedin-in pr-2"></i></a></li>
                    <li><a href="https://twitter.com/alice_gleizes"><i class="fab fa-twitter px-2"></i></a></li>
                    <li><a href="https://www.instagram.com/alice_glz/"><i class="fab fa-instagram pl-2"></i></a></li>
                  </ul>
              </div>
          </div>
          <div class="col-6 col-lg-4 col-md-6 col-sm-6 logo-wrapper">
              <a href="<%=root_path%>" class="logo_title">
                  <h1 class="">Le Mot de la <span style="color: #F07A80;">Bombe</span>.</h1>
              </a>
          </div>
          <div class="col-lg-4 col-md-6 col-sm-6 search-trigger">
              <div class="right-button">
                  <ul>
                    <!--  <li><a id="search" href="javascript:void(0)"><i class="fas fa-search"></i></a></li>
                      <li><a href="">About</a></li>
                      <li><a href="">Subscribe</a></li>-->
                  </ul>
              </div>
          </div>
      </div>
  </div>

  </section>
  <!--================ End header top Area =================-->
  <!-- Start header Menu Area -->
      <header id="header" class="header_area">
          <div class="main_menu">
              <nav class="navbar navbar-expand-lg navbar-light">
                  <div class="container">
                      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                          <span class="icon-bar"></span>
                          <span class="icon-bar"></span>
                          <span class="icon-bar"></span>
                      </button>
                      <!-- Collect the nav links, forms, and other content for toggling -->
                      <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
                          <ul class="nav navbar-nav menu_nav ml-auto mr-auto">
                              <li class="nav-item active"><a class="nav-link" href="<%=root_path%>">Accueil</a></li>
                              <li class="nav-item"><a class="nav-link" href="<%=root_path(anchor:"a-propos")%>">A Propos</a></li>
                              <li class="nav-item"><a class="nav-link" href="<%=categorie_path(1)%>">Visages</a></li>
                              <li class="nav-item"><a class="nav-link" href="<%=categorie_path(2)%>">Les Engagés</a></li>
                              <li class="nav-item"><a class="nav-link" href="<%=categorie_path(3)%>">Les Experts</a></li>
                              <li class="nav-item"><a class="nav-link" href="<%=little_berlins_path%>">Little Berlin(s)</a></li>
                              <!--<li class="nav-item submenu dropdown">
                                  <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Les Enag</a>
                                  <ul class="dropdown-menu">
                                      <li class="nav-item"><a class="nav-link" href="blog.html">Blog</a></li>
                                      <li class="nav-item"><a class="nav-link" href="single-blog.html">Blog Details</a></li>
                                  </ul>
                              </li>-->
                          </ul>
                      </div>
                  </div>
              </nav>
          </div>
      </header>
      <!-- End header MEnu Area -->

  <body>
    <%= yield %>





        <!-- ================ start footer Area ================= -->
        <footer class="footer-area">
            <div class="container">
                <div class="row mb-4 pb-4">

                    <div class="col-lg-3 col-sm-6 mb-4 mb-xl-0 single-footer-widget">
                        <h4>Alice Gleizes</h4>
                        <p>Incompris, ceux qui maîtrisent la bombe l’associent à un moyen d’expression, un engagement porté par la passion. </p>
                        <div class="footer-logo">
                            Le mot de la Bombe
                        </div>
                    </div>

                    <div class="col-lg-3 col-sm-6 mb-4 mb-xl-0 single-footer-widget">
                        <h4>Contact Info</h4>
                        <div class="footer-address">
                          <ul class="" style="display:flex; ">
                              <li><a href="https://www.linkedin.com/in/alice-gleizes-588642114/?originalSubdomain=fr"><i class="fab fa-linkedin-in pr-2"></i></a></li>
                              <li><a href="https://twitter.com/alice_gleizes"><i class="fab fa-twitter px-2"></i></a></li>
                              <li><a href="https://www.instagram.com/alice_glz/"><i class="fab fa-instagram pl-2"></i></a></li>
                          </ul>
                            <span>+33 648099783</span>
                            <span>alice.gleizes1@gmail.com</span>
                        </div>
                    </div>

                    <div class="col-lg-3 col-sm-6 mb-4 mb-xl-0 single-footer-widget">
                        <h4>Articles</h4>
                        <ul>
                            <li><a href="<%=categorie_path(1)%>">Les visages</a></li>
                            <li><a href="<%=categorie_path(2)%>">Les Engagés</a></li>
                            <li><a href="<%=categorie_path(3)%>">Les Experts</a></li>
                            <li><a href="<%=categorie_path(1)%>">Little Berlin(s)</a></li>
                        </ul>
                    </div>

                    <div class="col-lg-3 col-sm-6 col-md-6 mb-4 mb-xl-0 single-footer-widget">
                        <h4>Se connecter</h4>
                        <ul>
                          <% if user_signed_in? %>
                            <li>
                            <%= link_to "Nouvel Article", new_article_path %>
                            </li>
                            <li>
                            <%= link_to "Panel Admin", rails_admin_path %>
                            </li>
                            <li>
                              <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
                            </li>

                            <li>
                              Voici ton email : <%= current_user.email %>
                            </li>


                            <li>
                              <%= link_to "Edit email / password", edit_user_registration_path %>
                            </li>

                          <% else %>
                            <li>
                              <%= link_to "Sign in", new_user_session_path %>
                            </li>

                          <% end %>
                        </ul>

                </div>
            </div>

        </div>
    </footer>
    <!-- ================ End footer Area ================= -->


  </body>
</html>